# ---------------------------------------------------------------------------------
# Docker compose file for production, for enabling  this execute:
# docker-compose -f docker-compose.yml -f docker-compose.traefik.yml up -d --build
# OR
# Copy and rename this file as docker-compose.override.yml and run:
# docker-compose up -d --build
# ---------------------------------------------------------------------------------

version: "3.7"

services: 
